#!/bin/bash
### BEGIN INIT INFO
# Provides:          loginvsid
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: loginvsid
# Description:       loginvsid
### END INIT INFO

start() {
  /loginvsi/bin/start/start-pi
}

stop() { 
  /loginvsi/bin/stop/stop-pi
}

restart() {
 stop
 start
}

status() {   
  docker service ls -f name=VSI_   
}
update() {  
  /loginvsi/bin/update/update-pi "$2"
}



case "$1" in
  start|stop|restart|status) "$1" ;;
  update) "$1" "$@" ;;
  *)
  echo "Invalid arguments!"
  echo "Usage: $0 start|stop|restart|status"
  echo "Updating online : $0 update"
  echo "Updating offline: $0 update offline"  
  ;;
esac